# File: config_UprootRaw.yaml

Sample:
  - Name: UprootRaw_YAML
    Dataset: !FileList  
      [
        "root://eospublic.cern.ch//eos/opendata/atlas/rucio/data16_13TeV/DAOD_PHYSLITE.37019878._000001.pool.root.1",
        "root://eospublic.cern.ch//eos/opendata/atlas/rucio/data16_13TeV/DAOD_PHYSLITE.37019878._000002.pool.root.1",
        "root://eospublic.cern.ch//eos/opendata/atlas/rucio/data16_13TeV/DAOD_PHYSLITE.37019878._000003.pool.root.1",
      ]
    Query: !UprootRaw |
      [{"treename":"CollectionTree", "filter_name": "AnalysisElectronsAuxDyn.pt"}]