Definition:
  - &DEF_output_format root-ttree
  - &DEF_ttH_nominal_query !FuncADL_Uproot  |
    FromTree('mini').Select(lambda e: {'lep_pt': e['lep_pt']}).Where(lambda e: e['lep_pt'] > 1000)
  - &DEF_ggH_input "root://eospublic.cern.ch//eos/opendata/atlas/OutreachDatasets\
                  /2020-01-22/4lep/MC/mc_345060.ggH125_ZZ4lep.4lep.root"

General:
  OutputFormat: *DEF_output_format
  Delivery: LocalCache

Sample:
  - Name: ggH
    XRootDFiles: *DEF_ggH_input
    Query: *DEF_ttH_nominal_query
